theme: jekyll-theme-architect
## => Site Settings
##############################
text_skin: forest
highlight_theme: default
url     : https://hyunjoonkim.github.io
baseurl : 
title   : Hyunjoon Kim
description: >
  About Me
 
 
## => Language and Timezone
##############################
lang: ko
timezone: Asia/Seoul
 
 
## => Author and Social
##############################
author:
  type      : person
  name      : Hyunjoon Kim
  url       : 
  avatar    : 
  bio       : 
  email     :
  facebook  : 
  twitter   : 
  weibo     : 
  googleplus: 
  telegram  : 
  medium    : 
  zhihu     : 
  douban    : 
  linkedin  : 
  github    : hyunjoonkim
  npm       : Hyunjoon Kim
 
 
## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: hyunjoonkim/hyunjoonkim.github.io
repository_tree: master
 
 
## => Paths
##############################
paths:
  root    : /Benchmark_Problems_for_HRS_locations/
  home    : /Benchmark_Problems_for_HRS_locations/
  archive : 
  rss     : 
 
# ...
